# Generated by Django 5.0.6 on 2024-06-12 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_customer_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='order_id',
            new_name='order',
        ),
    ]
